title: "ExcelReader"
description: ExcelReader is a plugin that can read the file content in IDEs. Three formats of [xls, xlsx, csv] are supported.
remote_theme: pmarsceill/just-the-docs

aux_links:
  "GitHub":
    - "//github.com/obiscr/ExcelReader"
